"""Make shipping fields nullable

Revision ID: 04f93f2cb659
Revises: 5dec49d1a91e
Create Date: 2025-03-22 14:19:08.105586

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04f93f2cb659'
down_revision = '5dec49d1a91e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
