"""Fix billing address foreign key issue

Revision ID: 0f05383e7e48
Revises: 6af15715cd2d
Create Date: 2025-03-22 10:56:19.265544

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f05383e7e48'
down_revision = '6af15715cd2d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
