"""Fix billing address foreign key issue

Revision ID: 0f4f2ae365c8
Revises: 2c21732df4db
Create Date: 2025-03-22 11:00:27.973570

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f4f2ae365c8'
down_revision = '2c21732df4db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
