"""Fix billing address foreign key issue

Revision ID: 2c21732df4db
Revises: 0f05383e7e48
Create Date: 2025-03-22 10:57:42.077439

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c21732df4db'
down_revision = '0f05383e7e48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
