"""Added billing_address to Order

Revision ID: 2f6d07c852d0
Revises: d5f0548016d5
Create Date: 2025-03-22 10:41:13.151454

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f6d07c852d0'
down_revision = 'd5f0548016d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('billing_address_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'orders', 'billing_addresses', ['billing_address_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_column('orders', 'billing_address_id')
    # ### end Alembic commands ###
