"""Fix billing address foreign key issue

Revision ID: 33a5d4c4bdb5
Revises: 2f6d07c852d0
Create Date: 2025-03-22 10:52:30.636873

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33a5d4c4bdb5'
down_revision = '2f6d07c852d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'billing_address_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'billing_address_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
