"""Fix created_by and role nullable

Revision ID: 437582f3e5ce
Revises: a3866089e4e0
Create Date: 2025-03-12 15:29:07.405927

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '437582f3e5ce'
down_revision = 'a3866089e4e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'role',
               existing_type=postgresql.ENUM('SELLER', 'ADMIN', 'CUSTOMER', name='roleenum'),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'role',
               existing_type=postgresql.ENUM('SELLER', 'ADMIN', 'CUSTOMER', name='roleenum'),
               nullable=False)
    # ### end Alembic commands ###
