"""Make shipping fields nullable

Revision ID: 5dec49d1a91e
Revises: 8051575b4cd0
Create Date: 2025-03-22 14:15:22.757536

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5dec49d1a91e'
down_revision = '8051575b4cd0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
