"""Fix billing address foreign key issue

Revision ID: 6af15715cd2d
Revises: 33a5d4c4bdb5
Create Date: 2025-03-22 10:54:52.700930

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6af15715cd2d'
down_revision = '33a5d4c4bdb5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
