"""your message

Revision ID: 6fb680e5b35c
Revises: f653aee328a8
Create Date: 2025-03-19 12:16:00.534996

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6fb680e5b35c'
down_revision = 'f653aee328a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
