"""Make shipping fields nullable

Revision ID: 8051575b4cd0
Revises: ed7e1d38bdcb
Create Date: 2025-03-22 14:13:56.292760

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8051575b4cd0'
down_revision = 'ed7e1d38bdcb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_shipping_addresses_id', table_name='shipping_addresses')
    op.drop_table('shipping_addresses')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shipping_addresses',
    sa.Column('created_date', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('modified_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('status', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('seller_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('business_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('business_address', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('city', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('state', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('pincode', sa.VARCHAR(length=6), autoincrement=False, nullable=False),
    sa.Column('country', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['seller_id'], ['user.id'], name='shipping_addresses_seller_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='shipping_addresses_pkey')
    )
    op.create_index('ix_shipping_addresses_id', 'shipping_addresses', ['id'], unique=False)
    # ### end Alembic commands ###
