"""your message

Revision ID: 8d01c1faf519
Revises: 00028f85e19a
Create Date: 2025-03-24 15:52:38.440026

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d01c1faf519'
down_revision = '00028f85e19a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
