"""Make expiry_date nullable

Revision ID: c20716de4e3b
Revises: e713b208f3ee
Create Date: 2025-03-13 11:24:10.570757

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c20716de4e3b'
down_revision = 'e713b208f3ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'phone',
               existing_type=sa.VARCHAR(length=15),
               nullable=False)
    op.alter_column('user', 'gender',
               existing_type=sa.VARCHAR(length=15),
               nullable=False)
    op.alter_column('user', 'role',
               existing_type=postgresql.ENUM('SELLER', 'ADMIN', 'CUSTOMER', name='roleenum'),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('user', 'expiry_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=True)
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.drop_column('user', 'created_by')
    op.drop_column('user', 'modified_by')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('modified_by', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.alter_column('user', 'expiry_date',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('user', 'role',
               existing_type=sa.String(),
               type_=postgresql.ENUM('SELLER', 'ADMIN', 'CUSTOMER', name='roleenum'),
               existing_nullable=False)
    op.alter_column('user', 'gender',
               existing_type=sa.VARCHAR(length=15),
               nullable=True)
    op.alter_column('user', 'phone',
               existing_type=sa.VARCHAR(length=15),
               nullable=True)
    # ### end Alembic commands ###
