"""Fix billing address foreign key issue

Revision ID: cd45d0e0f481
Revises: dcadf4a1d7f8
Create Date: 2025-03-22 11:04:16.238859

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd45d0e0f481'
down_revision = 'dcadf4a1d7f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
