"""Fix product reference

Revision ID: ce773c9aaa78
Revises: 79eb8e154a0b
Create Date: 2025-03-19 12:19:28.968216

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce773c9aaa78'
down_revision = '79eb8e154a0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
