"""Add billing_address to user

Revision ID: d5f0548016d5
Revises: 4c91a5965a8a
Create Date: 2025-03-22 10:38:18.718116

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5f0548016d5'
down_revision = '4c91a5965a8a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
