"""Added user model

Revision ID: e713b208f3ee
Revises: 437582f3e5ce
Create Date: 2025-03-12 15:34:07.749302

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e713b208f3ee'
down_revision = '437582f3e5ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'role',
               existing_type=postgresql.ENUM('SELLER', 'ADMIN', 'CUSTOMER', name='roleenum'),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'role',
               existing_type=postgresql.ENUM('SELLER', 'ADMIN', 'CUSTOMER', name='roleenum'),
               nullable=True)
    # ### end Alembic commands ###
