"""Make shipping fields nullable

Revision ID: ed7e1d38bdcb
Revises: 784fdb532303
Create Date: 2025-03-22 12:44:35.350923

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed7e1d38bdcb'
down_revision = '784fdb532303'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('billing_addresses', 'shipping_contact_number')
    op.drop_column('billing_addresses', 'shipping_country')
    op.drop_column('billing_addresses', 'shipping_fullname')
    op.drop_column('billing_addresses', 'shipping_pincode')
    op.drop_column('billing_addresses', 'shipping_state')
    op.drop_column('billing_addresses', 'shipping_city')
    op.drop_column('billing_addresses', 'shipping_address')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('billing_addresses', sa.Column('shipping_address', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('billing_addresses', sa.Column('shipping_city', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('billing_addresses', sa.Column('shipping_state', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('billing_addresses', sa.Column('shipping_pincode', sa.VARCHAR(length=6), autoincrement=False, nullable=True))
    op.add_column('billing_addresses', sa.Column('shipping_fullname', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('billing_addresses', sa.Column('shipping_country', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('billing_addresses', sa.Column('shipping_contact_number', sa.VARCHAR(length=14), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
